modules/rbac/models/Role.php
<?php

namespace modules\rbac\models;

use Yii;
use yii\base\Model;
use modules\rbac\traits\ModuleTrait;
use modules\rbac\Module;

/**
 * Class Role
 * @package modules\rbac\models
 */
class Role extends Model
{
    use ModuleTrait;

    // константы ролей
    const ROLE_SUPER_ADMIN = 'super_admin';
    const ROLE_SUPER_ADMIN_DESCRIPTION = 'Super Administrator';

    const ROLE_ADMIN = 'admin';
    const ROLE_ADMIN_DESCRIPTION = 'Administrator';

    const ROLE_MANAGER = 'manager';
    const ROLE_MANAGER_DESCRIPTION = 'Manager';

    const ROLE_EDITOR = 'editor';
    const ROLE_EDITOR_DESCRIPTION = 'Editor';

    const ROLE_DEFAULT = 'user';
    const ROLE_DEFAULT_DESCRIPTION = 'User';

    // сценарии
    const SCENARIO_CREATE = 'create';
    const SCENARIO_UPDATE = 'update';

    public $name;
    public $description;
    public $isNewRecord = false;

    /** @var  array $rolesByRole Наследуемые роли */
    public $rolesByRole;
    /** @var  array $itemsRoles Доступные роли */
    public $itemsRoles;

    /** @var  array $permissionsByRole Установленные разрешения для роли */
    public $permissionsByRole;
    /** @var array $itemsPermissions Разрешения */
    public $itemsPermissions;

    /**
     * @inheritdoc
     * @return array
     */
    public function rules()
    {
        return [
            ['name', 'required', 'on' => self::SCENARIO_CREATE],
            ['name', 'string', 'max' => 64, 'on' => self::SCENARIO_CREATE],
            ['name', 'match', 'pattern' => '#^[\w_-]+$#i', 'message' => Module::t('module', 'It is allowed to use the Latin alphabet, numbers, dashes and underscores.(A-z,0-1,-,_)'), 'on' => self::SCENARIO_CREATE],
            ['name', 'validateUniqueName', 'skipOnEmpty' => false, 'skipOnError' => false, 'on' => [self::SCENARIO_CREATE]],

            [['description'], 'string'],
            [['rolesByRole', 'itemsRoles', 'permissionsByRole', 'itemsPermissions'], 'required', 'message' => Module::t('module', 'You must select in the field «{attribute}».'), 'on' => self::SCENARIO_UPDATE],
        ];
    }

    /**
     * @param string $attribute
     */
    public function validateUniqueName($attribute)
    {
        if (!$attribute) {
            $this->addError($attribute, Module::t('module', 'Enter name role.'));
        }
        if (!$this->hasErrors()) {
            $this->processCheckRoleName($attribute);
        }
    }

    /**
     * @param string $attribute
     * @return mixed
     */
    public function processCheckRoleName($attribute)
    {
        if (!empty($this->name)) {
            $auth = Yii::$app->authManager;
            if ($auth->getRole($this->name)) {
                $this->addError($attribute, Module::t('module', 'This name is already taken.'));
            }
        }
        return $attribute;
    }

    /**
     * @return array
     */
    public function scenarios()
    {
        $scenarios = parent::scenarios();
        $scenarios[self::SCENARIO_CREATE] = ['name', 'description'];
        $scenarios[self::SCENARIO_UPDATE] = ['name', 'description', 'rolesByRole', 'itemsRoles', 'permissionsByRole', 'itemsPermissions'];
        return $scenarios;
    }

    /**
     * @inheritdoc
     * @return array
     */
    public function attributeLabels()
    {
        return [
            'name' => Module::t('module', 'Name'),
            'description' => Module::t('module', 'Description'),
            'rolesByRole' => Module::t('module', 'Roles by role'),
            'itemsRoles' => Module::t('module', 'Items roles'),
            'permissionsByRole' => Module::t('module', 'Permissions by role'),
            'itemsPermissions' => Module::t('module', 'Items permissions'),
        ];
    }

    /**
     * @return array
     */
    public function getRolesArray()
    {
        return [
            self::ROLE_SUPER_ADMIN => self::ROLE_SUPER_ADMIN_DESCRIPTION,
            self::ROLE_ADMIN => self::ROLE_ADMIN_DESCRIPTION,
            self::ROLE_MANAGER => self::ROLE_MANAGER_DESCRIPTION,
            self::ROLE_EDITOR => self::ROLE_EDITOR_DESCRIPTION,
            self::ROLE_DEFAULT => self::ROLE_DEFAULT_DESCRIPTION,
        ];
    }

    /**
     * Возвращает установленные разрешения для роли
     * @return array
     */
    public function getPermissionsByRole()
    {
        $auth = Yii::$app->authManager;
        $perm = $auth->getPermissionsByRole($this->name);
        $arr = [];
        foreach ($perm as $value) {
            if ($value->name != $this->name) {
                $arr[$value->name] = $value->name . ' (' . $value->description . ')';
            }
        }
        return $arr;
    }

    /**
     * Возвращает все разрешения
     * @return array
     */
    public function getItemsPermissions()
    {
        $auth = Yii::$app->authManager;
        $perm = $auth->getPermissions();
        $arr = [];
        foreach ($perm as $value) {
            if ($value->name != $this->name) {
                $arr[$value->name] = $value->name . ' (' . $value->description . ')';
            }
        }
        $permByRole = $this->getPermissionsByRole();
        return array_diff($arr, $permByRole);
    }

    /**
     * Возвращает дочерние роли
     * @return array
     */
    public function getRolesByRole()
    {
        $auth = Yii::$app->authManager;
        $roles = $auth->getChildRoles($this->name);
        $arr = [];
        foreach ($roles as $value) {
            if ($value->name != $this->name) {
                $arr[$value->name] = $value->name . ' (' . $value->description . ')';
            }
        }
        return $arr;
    }

    /**
     * Возвращает все роли
     * @return array
     */
    public function getItemsRoles()
    {
        $auth = Yii::$app->authManager;
        $roles = $auth->getRoles();
        $arr = [];
        foreach ($roles as $value) {
            if ($value->name != $this->name) {
                $arr[$value->name] = $value->name . ' (' . $value->description . ')';
            }
        }
        $rolesByRole = $this->getRolesByRole();
        return array_diff($arr, $rolesByRole);
    }

    /**
     * @return \yii\rbac\Role[]
     */
    public function getRoleChild()
    {
        $auth = Yii::$app->authManager;
        return $auth->getChildRoles($this->name);
    }

    /**
     * Возвращает массив дочерних ролей
     * @return array
     */
    public function getRoleChildArray()
    {
        $roles = $this->getRoleChild();
        $arr = [];
        foreach ($roles as $value) {
            if ($value->name != $this->name) {
                $arr[$value->name] = $value->description;
            }
        }
        return $arr;
    }

    /**
     * Получаем все роли
     * @return \yii\rbac\Role[]
     */
    public function getRoles()
    {
        $auth = Yii::$app->authManager;
        return $auth->getRoles();
    }

    /**
     * Возвращает массив ролей
     * @return array
     */
    public function getRoleItemsArray()
    {
        $roles = $this->getRoles();
        $arr = [];
        foreach ($roles as $value) {
            if ($value->name != $this->name) {
                $arr[$value->name] = $value->description;
            }
        }
        return $arr;
    }

    /**
     *
     * @return array
     */
    public function getRolePermissions()
    {
        $auth = Yii::$app->authManager;
        $children = $auth->getChildren($this->name);
        $perm = [];
        foreach ($children as $key => $child) {
            if ($child->type == 2)
                $perm[$key] = $child;
        }
        return $perm;
    }

    /**
     * Все дети
     * @return \yii\rbac\Item[]
     */
    public function getChildren()
    {
        $auth = Yii::$app->authManager;
        return $auth->getChildren($this->name);
    }
}

modules/rbac/controllers/AssignController.php
<?php

namespace modules\rbac\controllers;

use Yii;
use modules\rbac\models\Assignment;
use yii\data\ArrayDataProvider;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\base\InvalidConfigException;
use yii\web\NotFoundHttpException;
use modules\rbac\Module;

/**
 * Class AssignController
 * @package modules\rbac\controllers
 */
class AssignController extends Controller
{
    /** @var $user object */
    private $_user = null;

    /**
     * @param \yii\base\Action $action
     * @return bool
     * @throws InvalidConfigException
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        if (empty(Yii::$app->controller->module->params['userClass'])) {
            throw new InvalidConfigException(Module::t('module', 'You must specify the User class in the module settings.'));
        }
        $this->_user = new Yii::$app->controller->module->params['userClass']();
        return parent::beforeAction($action);
    }

    /**
     * @inheritdoc
     * @return array
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['managerRbac'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'revoke' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * @return mixed
     */
    public function actionIndex()
    {
        $assignModel = new Assignment();
        $users = $this->_user->find()->all();
        $dataProvider = new ArrayDataProvider([
            'allModels' => $users,
            'sort' => [
                'attributes' => ['username', 'role'],
            ],
            'pagination' => [
                'pageSize' => 25,
            ],
        ]);
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'assignModel' => $assignModel,
        ]);
    }

    /**
     * @param string|int $id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionView($id)
    {
        $assignModel = new Assignment();
        return $this->render('view', [
            'model' => $this->findModel($id),
            'assignModel' => $assignModel,
        ]);
    }

    /**
     * @param string|int $id
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException
     * @throws \Exception
     */
    public function actionUpdate($id)
    {
        $model = new Assignment([
            'user' => $this->findModel($id)
        ]);
        if ($model->load(Yii::$app->request->post())) {
            $auth = Yii::$app->authManager;
            $role = $auth->getRole($model->role);
            // отвязываем роли если есть
            if ($auth->getRolesByUser($model->user->id)) {
                $auth->revokeAll($model->user->id);
            }
            // Привязываем новую роль
            if ($auth->assign($role, $model->user->id)) {
                return $this->redirect(['view', 'id' => $model->user->id]);
            }
        }
        $model->role = $model->getRoleUser($id);
        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * @param string|int $id
     * @return \yii\web\Response
     * @throws NotFoundHttpException
     */
    public function actionRevoke($id)
    {
        /** @var \modules\users\models\User $model */
        $model = $this->findModel($id);
        $auth = Yii::$app->authManager;
        if ($auth->getRolesByUser($model->id)) {
            if ($auth->revokeAll($model->id)) {
                Yii::$app->session->setFlash('success', Module::t('module', 'User "{:username}" successfully unassigned.', [':username' => $model->username]));
            } else {
                Yii::$app->session->setFlash('error', Module::t('module', 'Error!'));
            }
        } else {
            Yii::$app->session->setFlash('warning', Module::t('module', 'User "{:username}" is not attached to any role!', [':username' => $model->username]));
        }
        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string|int $id
     * @return null|\modules\users\models\User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        $userModel = $this->_user;
        if (($model = $userModel->findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException(Module::t('module', 'The requested page does not exist.'));
        }
    }
}

modules/rbac/controllers/DefaultController.php
<?php

namespace modules\rbac\controllers;

use Yii;
use yii\helpers\Url;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use modules\rbac\Module;

/**
 * Class DefaultController
 * @package modules\rbac\controllers
 */
class DefaultController extends \modules\rbac\console\InitController
{
    /**
     * @inheritdoc
     * @return array
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['managerRbac'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'init' => YII_ENV_TEST ? ['GET'] : ['POST'],
                ],
            ],
        ];
    }

    /**
     * Renders the index view for the module
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Переинициализация RBAC
     * с установкой настроек по умолчанию
     */
    public function actionInit()
    {
        if ($this->processInit()) {
            Yii::$app->session->setFlash('success', Module::t('module', 'The operation was successful!'));
        }
        Yii::$app->getResponse()->redirect(Url::to(['index']));
    }
}

modules/rbac/views/assign/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use modules\rbac\Module;

/* @var $this yii\web\View */
/* @var $model modules\rbac\models\Role */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="rbac-assign-form">

    <?php $form = ActiveForm::begin(); ?>

    <div class="row">
        <div class="col-md-5">
            <?= $form->field($model, 'role')->listBox($model->rolesArray, [
                'size' => 8
            ]) ?>
        </div>
    </div>
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? '<span class="glyphicon glyphicon-plus" aria-hidden="true"></span> ' . Module::t('module', 'Create') : '<span class="glyphicon glyphicon-ok" aria-hidden="true"></span> ' . Module::t('module', 'Save'), [
            'class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary'
        ]) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

modules/rbac/views/assign/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use yii\grid\GridView;
use modules\rbac\Module;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $assignModel \modules\rbac\models\Assignment */

$this->title = Module::t('module', 'Role Based Access Control');
$this->params['breadcrumbs'][] = ['label' => Module::t('module', 'RBAC'), 'url' => ['default/index']];
$this->params['breadcrumbs'][] = Module::t('module', 'Assign');
?>

<div class="rbac-assign-index">
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title"><?= Module::t('module', 'Assign') ?></h3>

            <div class="box-tools pull-right"></div>
        </div>
        <div class="box-body">
            <div class="pull-left"></div>
            <div class="pull-right"></div>
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'layout' => "{items}",
                'tableOptions' => [
                    'class' => 'table table-bordered table-hover',
                ],
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],
                    [
                        'attribute' => 'username',
                        'label' => Module::t('module', 'User'),
                        'format' => 'raw',
                    ],
                    [
                        'attribute' => 'role',
                        'label' => Module::t('module', 'Role'),
                        'format' => 'raw',
                        'value' => function ($data) use ($assignModel) {
                            return $assignModel->getRoleName($data->id);
                        }
                    ],
                    [
                        'class' => 'yii\grid\ActionColumn',
                        'contentOptions' => [
                            'class' => 'action-column'
                        ],
                        'template' => '{view} {update} {revoke}',
                        'buttons' => [
                            'view' => function ($url, $model) {
                                return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', Url::to(['view', 'id' => $model->id]), [
                                    'title' => Module::t('module', 'View'),
                                    'data' => [
                                        'toggle' => 'tooltip',
                                        'pjax' => 0,
                                    ]
                                ]);
                            },
                            'update' => function ($url, $model) {
                                return Html::a('<span class="glyphicon glyphicon-pencil"></span>', Url::to(['update', 'id' => $model->id]), [
                                    'title' => Module::t('module', 'Update'),
                                    'data' => [
                                        'toggle' => 'tooltip',
                                        'pjax' => 0,
                                    ]
                                ]);
                            },
                            'revoke' => function ($url, $model) {
                                $linkOptions = [];
                                /** @var object $identity */
                                $identity = Yii::$app->user->identity;
                                if ($model->id == $identity->id) {
                                    $linkOptions = [
                                        'style' => 'display: none;',
                                    ];
                                }
                                return Html::a('<span class="glyphicon glyphicon-remove"></span>', Url::to(['revoke', 'id' => $model->id]), ArrayHelper::merge([
                                    'title' => Module::t('module', 'Revoke'),
                                    'data' => [
                                        'toggle' => 'tooltip',
                                        'method' => 'post',
                                        'confirm' => Module::t('module', 'Do you really want to untie the user from the role?'),
                                    ],
                                ], $linkOptions));
                            },
                        ]
                    ],
                ],
            ]); ?>
        </div>
        <div class="box-footer"></div>
    </div>
</div>

modules/rbac/views/assign/update.php
<?php

use yii\helpers\Html;
use modules\rbac\Module;

/* @var $this yii\web\View */
/* @var $model modules\rbac\models\Assignment */

$this->title = Module::t('module', 'Role Based Access Control');
$this->params['breadcrumbs'][] = ['label' => Module::t('module', 'RBAC'), 'url' => ['default/index']];
$this->params['breadcrumbs'][] = ['label' => Module::t('module', 'Assign'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->user->username, 'url' => ['view', 'id' => $model->user->id]];
$this->params['breadcrumbs'][] = Module::t('module', 'Update');
?>

<div class="rbac-assign-update">
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title"><?= Module::t('module', 'Update') ?>
                <small><?= Html::encode($model->user->username) ?></small>
            </h3>
        </div>
        <div class="box-body">
            <?= $this->render('_form', [
                'model' => $model,
            ]) ?>
        </div>
        <div class="box-footer"></div>
    </div>
</div>

modules/rbac/views/assign/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use modules\rbac\Module;

/* @var $this yii\web\View */
/* @var $model modules\users\models\User */
/* @var $assignModel \modules\rbac\models\Assignment */

$this->title = Module::t('module', 'Role Based Access Control');
$this->params['breadcrumbs'][] = ['label' => Module::t('module', 'RBAC'), 'url' => ['default/index']];
$this->params['breadcrumbs'][] = ['label' => Module::t('module', 'Assign'), 'url' => ['index']];
$this->params['breadcrumbs'][] = Html::encode($model->username);
?>

<div class="rbac-assign-view">
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title"><?= Module::t('module', 'View') ?>
                <small><?= Html::encode($model->username) ?></small>
            </h3>
        </div>
        <div class="box-body">
            <div class="pull-left"></div>
            <div class="pull-right"></div>

            <div class="row">
                <div class="col-md-6">
                    <?= DetailView::widget([
                        'model' => $model,
                        'attributes' => [
                            'id',
                            [
                                'attribute' => 'username',
                                'label' => Module::t('module', 'User'),
                                'format' => 'raw',
                            ],
                            [
                                'attribute' => 'role',
                                'label' => Module::t('module', 'Role'),
                                'format' => 'raw',
                                'value' => function ($model) use ($assignModel) {
                                    return $assignModel->getRoleName($model->id);
                                },
                            ]
                        ],
                    ]) ?>
                </div>
                <div class="col-md-6">
                    <?php
                    /** @var string $role */
                    $role = $assignModel->getRoleUser($model->id);
                    $auth = Yii::$app->authManager;
                    if ($permissionsRole = $auth->getPermissionsByRole($role)) : ?>
                        <strong><?= Module::t('module', 'Permissions by role') ?></strong>
                        <ul>
                            <?php foreach ($permissionsRole as $value) {
                                echo Html::tag('li', $value->name . ' (' . $value->description . ')') . PHP_EOL;
                            } ?>
                        </ul>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <div class="box-footer">
            <p>
                <?= Html::a('<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> ' . Module::t('module', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
                <?= Html::a('<span class="glyphicon glyphicon-remove" aria-hidden="true"></span> ' . Module::t('module', 'Revoke'), ['revoke', 'id' => $model->id], [
                    'class' => 'btn btn-danger',
                    'data' => [
                        'confirm' => Module::t('module', 'Do you really want to untie the user from the role?'),
                        'method' => 'post',
                    ],
                ]) ?>
            </p>
        </div>
    </div>
</div>